- name : add application user
  ansible.builtin.user:
    name: roboshop

- name: clean old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: copy mongodb yum repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Download and extract application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes


