- name: setup dispatch service
  hosts: all
  become: true
  vars:
    component: dispatch
  tasks:
    - name: install golang
      ansible.builtin.yum:
        name: golang
        state: installed

    - name: app prerequistie
      ansible.builtin.import_tasks: appreq.yml

    - name: install the dependencies
      ansible.builtin.shell: go mod init dispatch

    - name: install the dependencies
      ansible.builtin.shell: go get

    - name: install the dependencies
      ansible.builtin.shell: go build

    - name: app prerequistie
      ansible.builtin.import_tasks: systemd.yml
