- name : Mongodb setup
  hosts: all
  become: true
  tasks:
   - name: copy mongodb yum repo file
     ansible.builtin.copy:
       src: mongo.repo
       dst: /etc/yum.repos.d/mongo.repo

   - name: install mongodb
     ansible.builtin.yum:
       name: mongodb-org
       state: installed

   - name: update listener address in mongodb configuration
     ansible.builtin.replace:
       path: /etc/mongod.conf
       regexp: '127.0.0.1'
       replace: '0.0.0.0'

   - name: restart
     ansible.builtin.systemd:
      - name: mongodb
        state: restarted
        enabled: yes
